FROM python:3.11.4-bookworm

ENV PYTHONUNBUFFERED 1

RUN pip3 install --upgrade pip
RUN pip3 install ipykernel
RUN pip3 install Django==3.2
RUN pip3 install numpy==1.25.2
RUN pip3 install pandas==2.0.3
RUN pip3 install joblib==1.3.2
RUN pip3 install numpy==1.23.5
RUN pip3 install matplotlib
RUN pip3 install scikit-learn==1.2.2
RUN pip3 install django djangorestframework
RUN pip3 install mlflow

WORKDIR /backend

COPY . /backend/

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]

